[mypy]
exclude = ^(\.venv|\.vscode|\.local|__pycache__|docmaker/macros/.*)/
python_version = 3.13
strict = False

[tool.mypy]
namespace-packages = True

[mypy-markdown2.*]
ignore_missing_imports = True

